# Generated by Django 5.1.1 on 2024-10-06 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_department_and_more'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(blank=True, null=True, to='registration.course')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.student')),
            ],
        ),
    ]
