# Generated by Django 5.1.1 on 2024-10-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_department_and_more'),
        ('registration', '0003_alter_cart_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='accepted_students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='requested_students',
        ),
        migrations.AddField(
            model_name='course',
            name='accepted_students',
            field=models.ManyToManyField(related_name='acc_students', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='requested_students',
            field=models.ManyToManyField(related_name='req_students', to='accounts.student'),
        ),
    ]
