# Generated by Django 5.1.1 on 2024-10-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_course_accepted_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electronics and Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CH', 'Chemical Engineering'), ('CV', 'Civil Engineering'), ('MME', 'Mining and Metallurgical Engineering')], default='CSE', max_length=50),
            preserve_default=False,
        ),
    ]
