# Generated by Django 5.1.1 on 2024-10-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_faculty_faculty_id_alter_student_student_id'),
        ('registration', '0006_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructors',
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(to='accounts.faculty'),
        ),
    ]
